# Generated by Django 4.1.3 on 2022-11-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=1000)),
                ('follower_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('bio', models.CharField(default='None', max_length=250)),
                ('no_followers', models.IntegerField(default=0)),
                ('no_following', models.IntegerField(default=0)),
                ('no_post', models.IntegerField(default=0)),
            ],
        ),
    ]
